// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHealth() {
  return window['go']['main']['App']['GetHealth']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetTunnelStatus() {
  return window['go']['main']['App']['GetTunnelStatus']();
}

export function Maximize() {
  return window['go']['main']['App']['Maximize']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function ResetStats() {
  return window['go']['main']['App']['ResetStats']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}

export function StartTunnel() {
  return window['go']['main']['App']['StartTunnel']();
}

export function StopTunnel() {
  return window['go']['main']['App']['StopTunnel']();
}
