// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Close():Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetHealth():Promise<Record<string, any>>;

export function GetStats():Promise<main.Stats>;

export function GetTunnelStatus():Promise<Record<string, string>>;

export function Maximize():Promise<void>;

export function Minimize():Promise<void>;

export function ResetStats():Promise<boolean>;

export function SaveConfig(arg1:main.Config):Promise<boolean>;

export function SetAPIKey(arg1:string):Promise<boolean>;

export function SetModel(arg1:string):Promise<boolean>;

export function StartTunnel():Promise<Record<string, any>>;

export function StopTunnel():Promise<boolean>;
